import org.springframework.web.bind.UnsatisfiedServletRequestParameterException;
public class FunctionUse2142 {
public void funcUse() {
UnsatisfiedServletRequestParameterException unsatisfiedservletrequestparameterexception = new UnsatisfiedServletRequestParameterException();
unsatisfiedservletrequestparameterexception.requestParameterMapToString(null);
}
}